spring.application.name=ldnc

# Paramètres de connexion
spring.datasource.url=jdbc:postgresql://localhost:5432/ldncdb
spring.datasource.username=postgres
spring.datasource.password=pablo

# Gestion automatique des tables (crée/modifie les tables selon tes classes Java)
spring.jpa.hibernate.ddl-auto=update

# Debugging : Affiche les requêtes SQL dans ta console Java (très utile pour voir ce qui se passe)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optionnel mais recommandé : force l'utilisation du dialecte Postgres récent
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect