spring.application.name=ldnc

# Configuration Base de données PostgreSQL
# Connextion à la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ldncdb
spring.datasource.username=postgres
spring.datasource.password=pablo
spring.datasource.driver-class-name=org.postgresql.Driver

# (Optionnelle) crée automatiquement les tables à partir des entités JPA (a enlever en prod : none, validate)
spring.jpa.hibernate.ddl-auto=update

# (Optionnelle) Affiche les requêtes SQL générées par Hibernate dans la console (pour les erreurs de requêtes)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (Optionnelle) Spécifie que la DB est en postgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect